# For now, to ease development, this config acts as the dev build. Eventually
# it will be renamed to docker-compose-dev.yaml, and docker-compose.yaml will
# be in place for non-dev builds.

version: '3.9'

services:
  api:
    build: ./src/api
    command: npm run dev:docker
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=${API_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_ACCOUNT_NUMBER=${AWS_ACCOUNT_NUMBER}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SQS_QUEUE_NAME=${AWS_SQS_QUEUE_NAME}
      - AWS_SQS_REQUEUE_DELAY=${AWS_SQS_REQUEUE_DELAY}
      - AWS_SQS_REQUEUE_MAX_RETRIES=${AWS_SQS_REQUEUE_MAX_RETRIES}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "localhost:${API_PORT}/healthcheck"
        ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./src/api/:/code
      # NOTE: Below exclusion for API may not be needed, but including for consistency since 'web' includes it.
      # Exclude host's node_modules for container and processor architecture compatibility.
      - /code/node_modules/
  db:
    image: postgres:15.4
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
        ]
      interval: 2s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '${DB_PORT}:5432'
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
  web:
    build: ./src/web
    command: npm run dev:docker
    depends_on:
      api:
        condition: service_healthy
    environment:
      - VITE_API_PORT=${VITE_API_PORT}
      - WEB_PORT=${WEB_PORT}
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    volumes:
      - ./src/web/:/code
      # Exclude host's node_modules for container and processor architecture compatibility.
      - /code/node_modules/

# volumes:
#   pgdata:
